using System;
using System.Runtime.Serialization;

namespace JWTAuth.Models
{
    [DataContract]
    public class Business
    {
        /// <summary>
        /// Business Identifier (Autogenerated).
        /// </summary>
        [DataMember]
        public Guid? BusinessId { get; set; }

        /// <summary>
        /// Name of the Business you want to create a return.
        /// </summary>
        [DataMember]
        public string BusinessNm { get; set; }

        /// <summary>
        /// EIN or SSN of business
        /// </summary>
        [DataMember]
        public string EINorSSN { get; set; }

        /// <summary>
        /// Employer's email address.
        /// </summary>
        [DataMember]
        public string Email { get; set; }

        /// <summary>
        /// Name of a person who could be contacted by the IRS if needed.
        /// </summary>
        [DataMember]
        public string ContactNm { get; set; }

        /// <summary>
        /// Type of business entity. The value must be ESTE, PART, CORP, EORG, SPRO. Optional for W2/1099 and required for Form 94x.
        /// </summary>
        [DataMember]
        public string BusinessType { get; set; }

        /// <summary>
        /// To indicate if your business got terminated
        /// </summary>
        [DataMember]
        public bool IsBusinessTerminated { get; set; }

    }
}
